import os
import re

# Paths
DOCS_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_JS = os.path.join(DOCS_DIR, '../docs-content.js')
INDEX_HTML = os.path.join(DOCS_DIR, '../index.html')

def get_page_key(filename):
    return filename.replace('.content.html', '')

def html_to_js_string(html):
    # Escape backticks for JS template strings
    return html.replace('`', '\\`')

def main():
    content_files = [f for f in os.listdir(DOCS_DIR) if f.endswith('.content.html')]
    # Ensure 'index' is always first if you want, or just sort them
    content_files.sort() 
    
    content_dict = {}
    page_keys = []

    for fname in content_files:
        key = get_page_key(fname)
        page_keys.append(key)
        with open(os.path.join(DOCS_DIR, fname), 'r', encoding='utf-8') as f:
            html = f.read()
            content_dict[key] = html_to_js_string(html)

    # --- 1. Update docs-content.js ---
    with open(OUTPUT_JS, 'w', encoding='utf-8') as out:
        out.write('// Auto-generated by patch.py\n')
        out.write('window.DOCS_CONTENT = {\n')
        for i, (key, html) in enumerate(content_dict.items()):
            comma = ',' if i < len(content_dict) - 1 else ''
            out.write(f'  "{key}": `{html}`{comma}\n')
        out.write('};\n')
    print(f"Updated {OUTPUT_JS}")

    # --- 2. Update pageMap in index.html ---
    if os.path.exists(INDEX_HTML):
        with open(INDEX_HTML, 'r', encoding='utf-8') as f:
            html_content = f.read()

        # Generate the new pageMap string
        map_entries = ",\n".join([f"            '{key}': '{key}'" for key in page_keys])
        new_page_map = f"const pageMap = {{\n// Generated by patch.py\n{map_entries}\n        }};"

        # Regex to find 'const pageMap = { ... };' including multiple lines
        # This looks for the start of the variable and stops at the first };
        pattern = r"const pageMap\s*=\s*\{.*?\};"
        
        updated_html = re.sub(pattern, new_page_map, html_content, flags=re.DOTALL)

        with open(INDEX_HTML, 'w', encoding='utf-8') as f:
            f.write(updated_html)
        print(f"Updated pageMap in {INDEX_HTML}")

if __name__ == '__main__':
    main()